/**
 * The app origin's response headers, in Cloudflare Pages `_headers` format.
 *
 * `apps/web/public/_headers` is the same policy with placeholder hosts, for
 * people who deploy by hand. `scripts/deploy.mjs` writes the real one into the
 * built directory, so a scripted deployment can never ship the placeholders.
 */

/**
 * @param {object} options
 * @param {string} options.apiOrigin     e.g. `https://api.liha.example.com`
 * @param {string} options.contentDomain e.g. `example.net`; previews are served
 *                                       from `<slug>--<version>.<contentDomain>`
 */
export function buildHeaders({ apiOrigin, contentDomain }) {
  const csp = [
    "default-src 'self'",
    "script-src 'self'",
    // Vite emits a handful of inline style attributes; scripts stay strict.
    // Google Fonts serves the handwriting faces the interface is drawn in. Two
    // hostnames, both Google's own, on an otherwise self-only policy.
    "style-src 'self' 'unsafe-inline' https://fonts.googleapis.com",
    "img-src 'self' data: blob:",
    "font-src 'self' data: https://fonts.gstatic.com",
    `connect-src 'self' ${apiOrigin}`,
    `frame-src https://*.${contentDomain}`,
    "worker-src 'self' blob:",
    "object-src 'none'",
    "base-uri 'none'",
    "form-action 'none'",
    "frame-ancestors 'none'",
  ].join('; ');

  return [
    '# Generated by scripts/deploy.mjs. Edit scripts/lib/headers.mjs instead.',
    '/*',
    `  Content-Security-Policy: ${csp}`,
    '  X-Content-Type-Options: nosniff',
    '  Referrer-Policy: strict-origin-when-cross-origin',
    '  X-Frame-Options: DENY',
    '  Permissions-Policy: camera=(), microphone=(), geolocation=(), payment=(), usb=()',
    '  Strict-Transport-Security: max-age=31536000; includeSubDomains',
    '',
  ].join('\n');
}
