/**
 * Review bridge injected into HTML previews.
 *
 * The uploaded document is untrusted and runs on its own origin inside a
 * sandboxed iframe, so it cannot reach the app's storage or the owner token.
 * This script is the only channel between the two, and it is deliberately
 * one-directional in what it exposes: it reports what a reviewer clicked, and
 * accepts nothing but display commands from the parent.
 *
 * Written as a plain string (no template literals, no backticks) so it can be
 * inlined into any HTML response without escaping surprises.
 */
export const BRIDGE_SCRIPT = [
  '(function () {',
  '  if (window.__lihaBridge) return;',
  '  window.__lihaBridge = true;',
  '  var mode = "browse";',
  '  var hoverBox = null;',
  '',
  '  function send(type, payload) {',
  '    try {',
  '      window.parent.postMessage(Object.assign({ source: "liha-bridge", type: type }, payload), "*");',
  '    } catch (error) { /* parent went away */ }',
  '  }',
  '',
  '  function cssEscape(value) {',
  '    if (window.CSS && window.CSS.escape) return window.CSS.escape(value);',
  '    return String(value).replace(/[^a-zA-Z0-9_-]/g, "\\\\$&");',
  '  }',
  '',
  '  function describe(el) {',
  '    var name = el.nodeName.toLowerCase();',
  '    if (el.id) return name + "#" + cssEscape(el.id);',
  '    var cls = (el.getAttribute("class") || "").trim().split(/\\s+/).filter(Boolean).slice(0, 2);',
  '    return cls.length ? name + "." + cls.map(cssEscape).join(".") : name;',
  '  }',
  '',
  '  function uniqueSelector(el) {',
  '    if (!(el instanceof Element)) return "";',
  '    if (el.id && document.querySelectorAll("#" + cssEscape(el.id)).length === 1) {',
  '      return "#" + cssEscape(el.id);',
  '    }',
  '    var parts = [];',
  '    var node = el;',
  '    while (node && node.nodeType === 1 && node !== document.documentElement) {',
  '      var part = node.nodeName.toLowerCase();',
  '      if (node.id && document.querySelectorAll("#" + cssEscape(node.id)).length === 1) {',
  '        parts.unshift("#" + cssEscape(node.id));',
  '        break;',
  '      }',
  '      var parent = node.parentElement;',
  '      if (parent) {',
  '        var siblings = [];',
  '        for (var i = 0; i < parent.children.length; i++) {',
  '          if (parent.children[i].nodeName === node.nodeName) siblings.push(parent.children[i]);',
  '        }',
  '        if (siblings.length > 1) part += ":nth-of-type(" + (siblings.indexOf(node) + 1) + ")";',
  '      }',
  '      parts.unshift(part);',
  '      node = node.parentElement;',
  '      if (parts.length > 8) break;',
  '    }',
  '    return parts.join(" > ");',
  '  }',
  '',
  '  function ancestorPath(el) {',
  '    var path = [];',
  '    var node = el;',
  '    while (node && node.nodeType === 1 && path.length < 24) {',
  '      path.unshift(describe(node));',
  '      node = node.parentElement;',
  '    }',
  '    return path;',
  '  }',
  '',
  '  var INTERESTING_ATTRS = ["href", "src", "alt", "title", "type", "name", "role", "aria-label", "data-testid"];',
  '',
  '  function attributesOf(el) {',
  '    var out = {};',
  '    for (var i = 0; i < INTERESTING_ATTRS.length; i++) {',
  '      var key = INTERESTING_ATTRS[i];',
  '      if (el.hasAttribute(key)) out[key] = String(el.getAttribute(key)).slice(0, 500);',
  '    }',
  '    return out;',
  '  }',
  '',
  '  function metrics() {',
  '    var doc = document.documentElement;',
  '    return {',
  '      scrollX: window.scrollX,',
  '      scrollY: window.scrollY,',
  '      scrollWidth: Math.max(doc.scrollWidth, window.innerWidth),',
  '      scrollHeight: Math.max(doc.scrollHeight, window.innerHeight),',
  '      innerWidth: window.innerWidth,',
  '      innerHeight: window.innerHeight,',
  '      devicePixelRatio: window.devicePixelRatio || 1,',
  '      path: location.pathname + location.search',
  '    };',
  '  }',
  '',
  '  function elementContext(el) {',
  '    var rect = el.getBoundingClientRect();',
  '    var text = (el.textContent || "").replace(/\\s+/g, " ").trim();',
  '    var snippet = "";',
  '    try { snippet = (el.outerHTML || "").slice(0, 1500); } catch (error) { snippet = ""; }',
  '    var classes = (el.getAttribute("class") || "").trim().split(/\\s+/).filter(Boolean).slice(0, 20);',
  '    return {',
  '      selector: uniqueSelector(el).slice(0, 1000),',
  '      tagName: el.nodeName,',
  '      id: el.id || undefined,',
  '      classList: classes.length ? classes : undefined,',
  '      textContent: text ? text.slice(0, 500) : undefined,',
  '      htmlSnippet: snippet || undefined,',
  '      attributes: attributesOf(el),',
  '      path: ancestorPath(el),',
  '      boundingRect: {',
  '        x: rect.left + window.scrollX,',
  '        y: rect.top + window.scrollY,',
  '        width: rect.width,',
  '        height: rect.height',
  '      }',
  '    };',
  '  }',
  '',
  '  function ensureHoverBox() {',
  '    if (hoverBox) return hoverBox;',
  '    hoverBox = document.createElement("div");',
  '    hoverBox.setAttribute("data-liha-overlay", "1");',
  '    var s = hoverBox.style;',
  '    s.position = "absolute";',
  '    s.pointerEvents = "none";',
  '    s.zIndex = "2147483647";',
  '    s.border = "2px solid #e11d48";',
  '    s.background = "rgba(225,29,72,0.08)";',
  '    s.borderRadius = "2px";',
  '    s.display = "none";',
  '    s.transition = "all 60ms ease-out";',
  '    document.body.appendChild(hoverBox);',
  '    return hoverBox;',
  '  }',
  '',
  '  function showHover(el) {',
  '    var box = ensureHoverBox();',
  '    var rect = el.getBoundingClientRect();',
  '    box.style.display = "block";',
  '    box.style.left = (rect.left + window.scrollX) + "px";',
  '    box.style.top = (rect.top + window.scrollY) + "px";',
  '    box.style.width = rect.width + "px";',
  '    box.style.height = rect.height + "px";',
  '  }',
  '',
  '  function hideHover() { if (hoverBox) hoverBox.style.display = "none"; }',
  '',
  '  function isOverlay(el) {',
  '    return !(el instanceof Element) || el.hasAttribute("data-liha-overlay");',
  '  }',
  '',
  '  document.addEventListener("mousemove", function (event) {',
  '    if (mode !== "review") return;',
  '    var el = event.target;',
  '    if (isOverlay(el)) return;',
  '    showHover(el);',
  '  }, true);',
  '',
  '  document.addEventListener("mouseleave", hideHover, true);',
  '',
  '  function pick(event) {',
  '    var el = event.target;',
  '    if (isOverlay(el)) return;',
  '    event.preventDefault();',
  '    event.stopPropagation();',
  '    var m = metrics();',
  '    send("element-picked", {',
  '      element: elementContext(el),',
  '      point: {',
  '        x: Math.min(1, Math.max(0, (event.clientX + window.scrollX) / m.scrollWidth)),',
  '        y: Math.min(1, Math.max(0, (event.clientY + window.scrollY) / m.scrollHeight))',
  '      },',
  '      metrics: m',
  '    });',
  '  }',
  '',
  '  // Picking on pointerdown rather than click gets the composer mounted and',
  '  // focused a whole mouse-press earlier, which is the difference between',
  '  // catching and dropping the first character someone types.',
  '  document.addEventListener("pointerdown", function (event) {',
  '    if (mode === "review") pick(event);',
  '  }, true);',
  '',
  '  // The click that follows must not navigate or activate anything.',
  '  document.addEventListener("click", function (event) {',
  '    if (mode !== "review") return;',
  '    if (isOverlay(event.target)) return;',
  '    event.preventDefault();',
  '    event.stopPropagation();',
  '  }, true);',
  '',
  '  // While reviewing, following a link would navigate away mid-annotation.',
  '  document.addEventListener("submit", function (event) {',
  '    if (mode === "review") { event.preventDefault(); event.stopPropagation(); }',
  '  }, true);',
  '',
  '  window.addEventListener("message", function (event) {',
  '    if (event.source !== window.parent) return;',
  '    var data = event.data;',
  '    if (!data || data.source !== "liha-app") return;',
  '    if (data.type === "set-mode") {',
  '      mode = data.mode === "review" ? "review" : "browse";',
  '      if (mode !== "review") hideHover();',
  '      send("mode-changed", { mode: mode });',
  '    } else if (data.type === "request-metrics") {',
  '      send("metrics", { metrics: metrics() });',
  '    } else if (data.type === "highlight") {',
  '      try {',
  '        var target = data.selector ? document.querySelector(data.selector) : null;',
  '        if (target) { showHover(target); target.scrollIntoView({ block: "center", behavior: "smooth" }); }',
  '        else hideHover();',
  '      } catch (error) { hideHover(); }',
  '    }',
  '  });',
  '',
  '  var throttled = false;',
  '  function reportMetrics() {',
  '    if (throttled) return;',
  '    throttled = true;',
  '    requestAnimationFrame(function () {',
  '      throttled = false;',
  '      send("metrics", { metrics: metrics() });',
  '    });',
  '  }',
  '  window.addEventListener("scroll", reportMetrics, { passive: true });',
  '  window.addEventListener("resize", reportMetrics);',
  '',
  '  function announce() { send("ready", { metrics: metrics() }); }',
  '  if (document.readyState === "loading") {',
  '    document.addEventListener("DOMContentLoaded", announce);',
  '  } else {',
  '    announce();',
  '  }',
  '  window.addEventListener("load", announce);',
  '})();',
].join('\n');

const INJECTION = `<script data-liha-bridge="1">${BRIDGE_SCRIPT}</script>`;

/** Largest HTML document we will rewrite; bigger ones are served untouched. */
const MAX_INJECT_BYTES = 8 * 1024 * 1024;

/**
 * Injects the bridge into an HTML document. Inline rather than a `<script src>`
 * so it works regardless of the document's base path.
 */
export function injectBridge(html: string): string {
  if (html.length > MAX_INJECT_BYTES) return html;
  if (html.includes('data-liha-bridge')) return html;
  const bodyClose = html.toLowerCase().lastIndexOf('</body>');
  if (bodyClose !== -1) {
    return html.slice(0, bodyClose) + INJECTION + html.slice(bodyClose);
  }
  const htmlClose = html.toLowerCase().lastIndexOf('</html>');
  if (htmlClose !== -1) {
    return html.slice(0, htmlClose) + INJECTION + html.slice(htmlClose);
  }
  return html + INJECTION;
}
